/**
 * Lean DOCX export (Phase 10) — a structured findings summary document, not
 * a full replica of the 14-section HTML report. Bug-bounty/pentest clients
 * that want a Word doc typically want the findings list and executive
 * narrative, not every raw graph query result — the HTML/PDF report remains
 * the complete artifact.
 */

import {
  Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell,
  TextRun, WidthType, AlignmentType, BorderStyle,
} from 'docx'
import type { ReportData } from './reportData'
import type { LLMNarratives } from './reportTemplate'

const SEVERITY_COLOR: Record<string, string> = {
  critical: 'B91C1C', high: 'C2410C', medium: 'A16207', low: '1D4ED8', info: '6B7280',
}

function cell(text: string, opts: { bold?: boolean; color?: string; width?: number } = {}): TableCell {
  return new TableCell({
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
    children: [new Paragraph({ children: [new TextRun({ text, bold: opts.bold, color: opts.color })] })],
  })
}

export async function generateReportDocx(data: ReportData, narratives: LLMNarratives | null): Promise<Buffer> {
  const children: (Paragraph | Table)[] = []

  children.push(
    new Paragraph({ text: 'Security Assessment Report', heading: HeadingLevel.TITLE }),
    new Paragraph({ text: data.project.targetDomain || data.project.name, heading: HeadingLevel.HEADING_2 }),
    new Paragraph({ text: `Generated ${new Date(data.generatedAt).toLocaleString()}`, spacing: { after: 400 } }),
  )

  if (narratives?.executiveSummary) {
    children.push(
      new Paragraph({ text: 'Executive Summary', heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: narratives.executiveSummary, spacing: { after: 300 } }),
    )
  }

  children.push(
    new Paragraph({ text: 'Risk Summary', heading: HeadingLevel.HEADING_1 }),
    new Paragraph({
      text: `Overall risk: ${data.metrics.riskLabel} (${data.metrics.riskScore}/100) — `
        + `${data.metrics.criticalCount} critical, ${data.metrics.highCount} high, `
        + `${data.metrics.mediumCount} medium, ${data.metrics.lowCount} low findings.`,
      spacing: { after: 300 },
    }),
  )

  children.push(new Paragraph({ text: 'Findings', heading: HeadingLevel.HEADING_1 }))

  if (data.remediations.length === 0) {
    children.push(new Paragraph({ text: 'No findings recorded for this project.' }))
  } else {
    const headerRow = new TableRow({
      tableHeader: true,
      children: [
        cell('Severity', { bold: true, width: 12 }),
        cell('Title', { bold: true, width: 38 }),
        cell('Category', { bold: true, width: 15 }),
        cell('Verdict', { bold: true, width: 15 }),
        cell('Status', { bold: true, width: 20 }),
      ],
    })

    const rows = data.remediations.map(r => new TableRow({
      children: [
        cell(r.severity.toUpperCase(), { color: SEVERITY_COLOR[r.severity] || '000000' }),
        cell(r.title),
        cell(r.category),
        cell(r.validatorStatus?.replace(/_/g, ' ') || 'needs manual review'),
        cell(r.status.replace(/_/g, ' ')),
      ],
    }))

    children.push(new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
      },
      rows: [headerRow, ...rows],
    }))

    // Per-finding detail, one heading block each — solution + business impact
    // when present (Phase 09 validator fields).
    for (const r of data.remediations) {
      children.push(
        new Paragraph({ text: r.title, heading: HeadingLevel.HEADING_2, spacing: { before: 300 } }),
        new Paragraph({ text: r.description }),
      )
      if (r.businessImpact) {
        children.push(new Paragraph({ children: [new TextRun({ text: 'Business impact: ', bold: true }), new TextRun(r.businessImpact)] }))
      }
      if (r.solution) {
        children.push(new Paragraph({ children: [new TextRun({ text: 'Suggested fix: ', bold: true }), new TextRun(r.solution)] }))
      }
    }
  }

  if (narratives?.recommendationsNarrative) {
    children.push(
      new Paragraph({ text: 'Recommendations', heading: HeadingLevel.HEADING_1, spacing: { before: 400 } }),
      new Paragraph({ text: narratives.recommendationsNarrative }),
    )
  }

  children.push(new Paragraph({
    text: 'Generated by DNM-Hunter — Automated Security Assessment Platform',
    alignment: AlignmentType.CENTER,
    spacing: { before: 600 },
  }))

  const doc = new Document({ sections: [{ children }] })
  return Packer.toBuffer(doc)
}
